# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca60111b9c03986ea16f115162c0f9d618f395d5eed32db750dcc5f20c24cb98680d95d0a0847ea4d2fa1a12bc05ec8d07fe02d53d75287c0f6f120997f058c2

test:
  secret_key_base: d8200eb8ac47d1a810774150463394692dc7c17519594feb3186489abbe82d7abeac6ba907d800ad997ae29a9775ee3ae33b46ff1d0e3ca76166f06858b89d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
